# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Week-4_Part-1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'KeychainAccess'
  # Pods for Week-4_Part-1

end
